server:
  port: 9000

spring:
  application:
    name: th-admin
  jackson:
    time-zone: GMT+8
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://114.55.54.77:3306/th-admin?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: fs
      password: Aa@123456
      initial-size: 5
      min-idle: 15
      max-active: 30
      remove-abandoned-timeout: 180
      max-wait: 3000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: select 1
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  flyway:
    # Flyway 和 Druid 的防 SQL 注入机制有冲突
    enabled: false
    encoding: UTF-8
    clean-disabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 230526.1
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: 114.55.54.77
    port: 6379
    password: Aa@123456
    connect-timeout: 5000